services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py makemigrations && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/app
    ports:
      - "80:80"
    environment:
      MYSQL_DATABASE: "cynthias_codex"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "verysecret"
      MYSQL_HOST: "10.0.1.111"
      MYSQL_PORT: 3306

      DJANGO_SETTINGS_MODULE: CynthiasCodex.settings

      AWS_BUCKET_NAME: "bronze-bucket-8"
      AWS_REGION: "us-east-1"
    restart: on-failure
