services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py makemigrations && python manage.py collectstatic && python manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/app
    ports:
      - "80:80"
    environment:
      - MYSQL_DATABASE=cynthias_codex
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_HOST=10.0.1.231
      - MYSQL_PORT=3306

      - DJANGO_SETTINGS_MODULE=CynthiasCodex.settings

      - AWS_ACCESS_KEY_ID=ASIAUWEMPCBHFILBB6PT
      - AWS_SECRET_ACCESS_KEY=5bbvwDXyHYL7i0uuWKegCuLHhlqb4zLZmAhGIWhY
      - AWS_BUCKET_NAME=s3-edu-licao
      - AWS_REGION="us-east-1"
      - AWS_STORAGE_BUCKET_NAME=s3-edu-licao
    restart: on-failure
